### ISSUE TITLE
Feature: tailwind 공통 theme 설정 및 svg 포함

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#105]
## Feature Description
- font sets
- color sets
- svg 아이콘

## To-Do

- [x] font sets 구성
- [x] color sets 구성
- [x]  svg 아이콘, 이미지 프로젝트에 포함
- [x]  파비콘 설정
