### ISSUE TITLE
Feature: DB에 있는 user라면 token을 발행한다.

### ISSUE THREAD

**Issue by tmddus2** [boostcampwm2023/web13_Boarlog#114]
## Feature Description

DB에 있는 사용자라면 회원가입이 되어있는 사용자이기 때문에 JWT 토큰을 발행한다.
만약 DB에 없는 사용자라면 최초 로그인된 사용자이기 때문에 구글에서 받아온 회원정보를 활용하여 회원가입을 시켜준다.

## To-Do

- [x] JWT 토큰 발행
- [x] DB에 user 확인
- [x] 회원가입 기능 구현
