### ISSUE TITLE
Feature: 버튼 component와 다이얼로그 component를 사용할 수 있다.

### ISSUE THREAD

**Issue by LellowMellow** [boostcampwm2023/web13_Boarlog#122]
## Feature Description
버튼과 다이얼로그 공용 컴포넌트 구성

## To-Do
- [x] Button 공용 컴포넌트를 구현한다.
- [x] Modal 공용 컴포넌트를 구현한다.
- [x] 추가: header와 연결하여 강의 종료 시 모달을 표시하도록 한다.
- [x] 추가: 공용 컴포넌트 테스트 페이지를 추가한다.
- [x] 추가: button과 modal의 버튼 style을 간단히 지정할 수 있도록 변경한다.
- [x] 추가: 접근성 향상을 위해 aria-label을 button 컴포넌트에 지정할 수 있도록 한다. 

### Button 공용 컴포넌트 구현

![image](https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/c84eacc8-2c9d-4a4c-a93c-85b172add76e)

`type`을 구분하여 활용할 수 있도록 하였습니다. 크게 3가지 `type`으로 `fit`, `full`, `grow`로 구분하여 사용이 가능합니다. 추가로 `hover`시에 색상이 변경되도록 `opacity`을 활용하였습니다.

### Modal 공용 컴포넌트 구현

```css
.dimmer {
  background: hsla(230, 4%, 8%, 0.8);
}

.display-center {
  @apply fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2;
}
```

`opacity` 값이 포함된 color를 배경으로 지정하기 위해 `global.css`에 `dimmer` class를 정의하였습니다. 또한 `fixed`로 position을 지정하여 수직 중앙 정렬을 위한 css class도 정의하여 Modal 구현에 활용하였습니다.

![image](https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/6b0b4203-c4f1-48df-8e32-71c4a0b39aa2)

```jsx
// Modal 사용 예시
<Modal
        modalText="모달에 표시되는 텍스트"
        cancelText="취소"
        confirmText="확인"
        cancelButtonStyle="black"
        confirmButtonStyle="red"
        confirmClick={() => console.log("확인 버튼 클릭")}
        isModalOpen={isModalOpen}
        setIsModalOpen={setIsModalOpen}
      />
```

Modal 컴포넌트는 state와 연결하여 특정 버튼을 클릭했을 경우에 표시되도록 구현하였습니다. 상단과 같이 작성하여 Modal을 사용할 수 있습니다.

### 버튼 스타일링 변경, aria-label 추가

![image](https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/8ebaea83-91d3-4b99-9c54-1ba471687509)

`ariaLabel` 속성을 추가하여 aria-label을 지정할 수 있도록 button을 수정하였습니다. 추가적으로 크게 4가지 style의 버튼으로 제한하여 쉽게 스타일을 지정할 수 있도록 하였습니다.

### 공용 컴포넌트 테스트 페이지 구성

공용 컴포넌트 작업 내역과 사용 방식을 쉽게 확인할 수 있는 페이지를 간단히 구성하였습니다. 이후 페이지 개발에 있어서 해당 페이지를 참고하여 개발을 진행해주시면 됩니다.

### 리뷰 반영 전 작업 내역

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/33fc4640-0701-4324-9b7f-55c541ae3fd3

### 공용 컴포넌트 테스트 페이지

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/000a7340-9707-47c4-a019-54c6d8d67e2e
