### ISSUE TITLE
Feature: Toast 공용 컴포넌트 구현

### ISSUE THREAD

**Issue by LellowMellow** [boostcampwm2023/web13_Boarlog#126]
## Feature Description
- Toast 공용 컴포넌트 구현

## To-Do
- [x] 전역 상태 관리 atom 작성
- [x] usePortal 작성
- [x] useToast 작성
- [x] ToastContainer 작성
- [x] Toast UI 작업
- [x] Toast 생성/삭제 애니메이션 추가
- [x] ~~Toast 표시 개수 제한 작업 (제거, 토스트 개수 제한 없음)~~
- [x] ~~useToast를 toast method로 사용할 수 있도록 작업 (보류)~~
- [x] 추가: 필요 없는 계층 제거
- [x] 추가: Toast 클릭 시에 메세지 제거 기능 추가
- [x] 추가: header 로고 이미지 alt 속성 추가
- [x] 추가: netlify.toml 추가

### 추가 사항
Toast를 프로젝트에서 활용할 때는 이전까지 `react-simple-toasts` 등의 라이브러리를 사용하였습니다. 직접 구현하기에 앞서 `react-simple-toasts`는 어떻게 동작하는지를 다시 확인해보았습니다.

> [🔗 react-simple-toasts github repository](https://github.com/almond-bongbong/react-simple-toasts)

![image](https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/158406a1-ea53-42d1-8b08-a80f6bfca5c2)

우선 root 내부에서 Toast를 관리하는 것이 아닌, 바깥에서 관리하는 것을 확인할 수 있습니다. 또한 Toast의 위치별로 container를 두어 Toast 생성 시에 해당 div 태그 내부에서 생성하도록 함을 확인할 수 있었습니다. 또한 특정 시간이 지나면 생성한 요소를 다시 삭제하여 각 container는 비어있는 상태를 유지하도록 동작하고 있습니다.

### 고민 1: 전역으로 관리해야 하는가?

Toast는 페이지 곳곳에서 사용됩니다. 버튼을 클릭하거나, 특정 페이지로 이동했을 경우 등 다양한 event와 연결지어 사용자에게 정보를 전달해주는 역할을 담당하고 있습니다. Toast의 내용을 지역적으로 관리할 경우, component의 형태로 각 페이지마다 가져와 사용해야 합니다.

다만, 페이지에서 페이지로 이동하는 과정에서 Toast를 사용하게 된다면 어떻게 될까요? 페이지 전체가 새로 그려지기 때문에 당연히 이동하기 전 페이지에서 ‘환영합니다’와 같은 메세지를 Toast로 전달한다고 하더라도 이후 페이지로 이동하면서 Toast가 사라지게 될 것입니다.

또한 각 페이지마다 state를 각각 만들어 관리해야 하기 때문에 복잡해지는 것은 물론, 페이지의 하위 component에서 Toast를 사용하기 위해 state를 prop로 전달해주는 과정에서의 prop dilling도 문제가 될 수 있습니다.

이러한 Toast state를 전역에서 관리해준다면 문제를 해결할 수 있습니다. 공통된 state를 공유하기 때문에 각 페이지에서 state를 따로 가지고 있을 필요도 없으며, 하위로 전달해줄 state가 없기 때문에 Toast state와 관련된 prop drilling을 신경쓰지 않을 수 있습니다.

### 고민 2: 부리 밖에서 그려야 하는가?

일반적으로 React에서 element는 `root` 하위의 DOM 계층 구조의 자식으로 렌더링됩니다. 다만, Toast는 ‘알림’의 기능을 담당하기 때문에 모든 요소의 최상단에 표시되어야 합니다. 물론 `z-index`와 `position: fixed` 등을 이용하여 이를 표시할 수 있지만, 불필요한 요소가 추가적으로 필요할 수 있음은 물론, 의도한 방식으로 작동하지 않을 가능성도 있습니다.

이를 부모 트리 밖으로 구분하여 관리한다면 이러한 문제 혹은 이슈를 해결할 수 있습니다.

React에서는 `createPortal`이라는 방법을 제공하고 있습니다. 이를 활용하면 DOM 계층 구조 바깥의 DOM 노드 하위에 특정 요소들을 렌더링할 수 있도록 할 수 있습니다.

```jsx
render() {
  // React는 새로운 div를 생성하지 *않고* `domNode` 안에 자식을 렌더링합니다.
  // `domNode`는 DOM 노드라면 어떠한 것이든 유효하고, 그것은 DOM 내부의 어디에 있든지 상관없습니다.
  return ReactDOM.createPortal(
    this.props.children,
    domNode
  );
}
```

이렇게 작성한 Toast는 component에서 다음과 같이 활용할 수 있습니다.

```jsx
const showToast = useToast();

...

<button onClick={() => showToast({ message: "경고 메세지", type: "alert" })}>
     Alert Toast
</button>
```

버튼을 클릭하여 showToast를 통해 Toast 메세지를 toastListState에 추가하여 Toast가 표시됩니다. 지금까지 구현한 Toast의 동작 과정을 표현하면 아래와 같습니다.

![image](https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/d64a9042-c590-4e2a-9e35-ae0626e446d2)

### Toast 생성, 일정 시간 이후 삭제, 클릭 시 삭제
https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/b902f571-6513-4ff3-9714-ee523010fd69
