### ISSUE TITLE
Feature: DB에서 입장 코드를 관리 & 강의실 입장 시 수강한 강의 목록에 추가

### ISSUE THREAD

**Issue by platinouss** [boostcampwm2023/web13_Boarlog#139]
## Feature Description

사용 중인 입장 코드 반환을 방지하기 위해, 현재 사용 중인 입장 코드를 DB에서 관리하고, 유저의 수강한 강의 목록을 확인할 수 있도록 기능을 추가한다.

## To-Do

- [x] 강의 참여 코드 생성 시, DB에서 사용 중인 참여 코드인지 확인
- [x] 강의 생성 후, 참여 코드를 DB에 추가
- [x] 유저가 강의실 입장 시, 수강한 강의 목록에 해당 강의 추가
