### ISSUE TITLE
Feature: 메인 페이지 강의 생성/참여하기 카드를 사용자가 확인할 수 있다 (UI 작업)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#16]
## Feature Description
메인 페이지 기본 UI 작업 close #16

## To-Do

- [ ] 메인 페이지 카드 flip 애니메이션 작업
- [ ] 메인페이지 강의 생성 입력 UI 작업
- [ ] 메인페이지 강의 참여 입력 UI 작업
