### ISSUE TITLE
Feature: 강의코드로 강의 정보를 조회한다.

### ISSUE THREAD

**Issue by tmddus2** [boostcampwm2023/web13_Boarlog#173]
## Feature Description

강의에 참여하기 전에 강의코드를 사용하여 강의 정보를 조회합니다.
사용자가 강의코드 조회를 하면 강의 정보를 보여주며 강의 참여 버튼이 보이게 됩니다. 사용자는 강의 참여 버튼을 눌러 강의에 참여할 수 있습니다. 

## To-Do

- [x] 강의 코드로 강의 조회
- [x] 강의 코드에 대응되는 강의 있으면 강의 정보 반환
- [x]  강의 코드에 대응되는 강의 없으면 에러 반환
