### ISSUE TITLE
Feature: 강의 종료 시 발표자의 영상·음성 스트림을 파일로 저장한다.

### ISSUE THREAD

**Issue by platinouss** [boostcampwm2023/web13_Boarlog#180]
## Feature Description

다시보기 기능을 위해, 발표자가 강의 내용과 음성을 파일로 추출한다.

## To-Do

- [x] 발표자의 영상 및 음성을 일정 단위로 추출한다.
- [x] 추출한 데이터를 버퍼에 저장한다.
- [x] 강의 종료 시 저장되어 있던 영상·음성을 하나의 파일로 추출한다.
