### ISSUE TITLE
Feature: 404 페이지를 확인할 수 있고, 버튼을 클릭하여 메인 페이지로 이동할 수 있다.(UI 작업 포함)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#24]
## Feature Description
404 Error 페이지 작업 #24

## To-Do
- [x] Error 페이지 UI 작업 (반응형)
- [x] Error 페이지 Redirect 작업
- [x] Error 페이지 바탕으로 강의 종료 페이지 UI 작업
