### ISSUE TITLE
Feature: 발표자 재접속 시 해결되지 않은 질문과 최신 화이트보드 데이터를 전달한다.

### ISSUE THREAD

**Issue by platinouss** [boostcampwm2023/web13_Boarlog#243]
## Feature Description

강의 도중 네트워크 문제로 발표자가 재접속 했을 경우, 참여자의 질문 리스트와 최신 화이트보드 정보가 있다면 원활하게 강의를 진행할 수 있게 됩니다.

따라서 미디어 서버는 발표자가 재접속 하는 경우를 판별하고, 적절한 데이터를 전달해주는 기능을 추가하려고 합니다.

## To-Do

- [ ] 접속한 클라이언트가 현재 발표 중인 발표자인지 확인한다.
- [ ] Redis의 강의실 화이트보드 stream에서 최신 화이트보드 데이터를 가져온다.
- [ ] 질문 보류 리스트(pending list)에서 ACK 요청을 받지 않은 모든 질문을 가져온다.
- [ ] 해결되지 않은 질문과 최신 화이트보드 데이터를 발표자에게 전달한다.
