### ISSUE TITLE
Feature: 포스트잇의 색상, 글꼴 등을 편집할 수 있다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#49]
## Feature Description
포스트잇 색, 글꼴 편집 기능 close #49

## To-Do
- [x] 기존 메모지가 그냥 사각형이기 때문에 텍스트를 입력할 수 있도록 구현(일단 수정은 불가)
- [x] 편집 패널 UI 작업
![Image](https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/9d99f5e3-e8ba-4c7c-8982-87351b85050c)
  - 메모 편집 패널 UI 작업
  - 메모지 색상 변경 패널 UI작업
  - 각 버튼 선택 기능 구현
  - 색상 팔레트 토글기능구현
  - 추가: 접근성을 위해 aria-pressed, aria-expanded 추가
- [x] 포스트잇 색 변경 기능 구현

https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/eebd31b9-8bd4-4e10-bd89-e9891b8e3aaf

- [x] 글꼴(폰트 사이즈, 폰트 정렬 기능)관련 기능 구현

https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/1b80bd5b-7884-428f-8d73-bacb2654d7c3

- [x] 포스트잇 삭제 기능 구현

https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/3f3121b5-31aa-4852-a205-35ae263274e1
