### ISSUE TITLE
Feature: 마우스로 화이트보드에 선을 그릴 수 있다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#50]
## Feature Description

여기에 작성하세요

## To-Do
- [x] Fabric.js로 화이드보드를 생성할 수 있다.
- [x] 화이트보드가 사용자의 브라우저 창 크기에 맞춰 재조정 된다.
- [x] 화이트보드 왼쪽 상단에 툴바를 띄워 놓을 수 있다.
- [x] 펜 버튼을 눌러 그리기모드로 전환, 펜 기능을 사용 할 수 있다.
- [x] 그려진 펜의 내용들을 선택 후 delete 키를 눌러 삭제할 수 있다.

### 추가 사항

여기에 작성하세요
