### ISSUE TITLE
Feature: 선의 색상을 변경할 수 있다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#51]
## Feature Description

여기에 작성하세요

## To-Do

- [x] CanvasSection 컴포넌트에서 툴바 컴포넌트의 state와 사이드이펙트 분리
- [x] 펜 색 선택 컬러패널 UI 구현
- [x] recoil로 fabric.Canvas 인스턴스 전역 state로 관리 
- [x] 체크 UI 구현
- [x] 펜 색 선택 기능 구현

#### CanvasSection 컴포넌트에서 툴바 컴포넌트의 state와 사이드이펙트 분리를 진행했습니다.

<CanvasSection /> 컴포넌트에서 <ToolBar/> 컴포넌트와의 props drilling을 해결하고 state 결합도 분리를 위해 해당 작업을 진행했습니다. 아래 사진과 같이 CanvasSection 컴포넌트에서는 activeTool이라는 state를 가지고는 있지만 실질적으로 상태를 set, get하고 있지는 않았습니다. 그래서 추후 진행할 툴들의 기능(메모지 생성, 펜 모드 활성화 등등)의 함수화 또는 모듈화를 통한 관심사의 분리와 props drilling을 방지하기 위해 state의 분리를 진행했습니다.

![image](https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/067c60d7-5b89-4ff3-9fa4-0f0e49075bec)

#### 펜 색 선택 모달 UI 구현

  ![ezgif com-video-to-gif (11)](https://github.com/boostcampwm2023/web13_Boarlog/assets/54176384/10ea11f4-a357-413a-ae49-7b95c4e981c4)
