### ISSUE TITLE
Feature: HTTPS 프로토콜 적용한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#6]
## Feature Description

배포된 프로젝트에 HTTPS 적용을 진행했습니다. webRTC 사용하는 과정에서 HTTPS 적용이 필요하다고 판단해 먼저 해당 작업을 수행했습니다.

## To-Do

- [x] 백엔드 서버가 실행 중인 클라우드 서버 내에서 Nginx 설치
- [x] SSL 인증서 발급
- [x] Nginx로 HTTP 접근은 HTTPS로 redirect

### 추가 사항

클라우드 서버에서 작업해준 내용이라 코드 상 특별한 업데이트는 없습니다. 이대로 issue close 하겠습니다!
