### ISSUE TITLE
Feature: 프로필 버튼을 클릭하면 사용자 정보 모달을 표시한다.(UI작업)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#60]
## Feature Description
Header component를 분리하고, 사용자 정보 모달을 표시하도록 UI를 구성한다.

## To-Do
- [x] Header component 분리
- [x]  Left/Right Section으로 구분
- [x] 사용자 정보 모달 UI 작업
- [x] 기존 Header와 연결, click event와 state 작업

### 추가 사항
- `tab`으로 button focus시에 모달이 활성화됨을 방지하기 위해 background 요소를 추가하여 이를 클릭할 경우에 모달을 비활성화하도록 수정하였습니다.
