### ISSUE TITLE
Feature: 마이페이지 버튼을 클릭하면 마이페이지로 이동한다. 로고를 클릭하면 메인화면으로 이동한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#62]
## Feature Description
메인 페이지 header에서 로고와 마이페이지 버튼을 클릭하면 해당 페이지로 이동하도록 한다.

## To-Do
- [x] useNavigate를 활용하여 메인 페이지로 이동하도록 작업
- [x] 마이페이지 파일 생성
- [x] useNavigate를 활용하여 마이페이지로 이동하도록 작업

### 추가 사항
~~없음~~
