### ISSUE TITLE
Feature: 강의자 페이지의 헤더를 표시할 수 있다. (강의 제목, 코드, 강의 시작/종료, 음소거, 설정)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#64]
## Feature Description
강의자 페이지의 header 요소 UI를 구현한다.

## To-Do
- [x] 강의자 페이지 header 요소 UI 구현
- [x] header 컴포넌트 구조 변경(`type` 추가)
- [x] `boolean` 타입 변수 네이밍 변경
- [x] `setting` 버튼 클릭 시 모달 임시 추가

### 추가 사항
- header component 구조를 변경하였습니다. `type`으로 지정하여 보다 편하게 header component를 사용할 수 있도록 구성하였습니다.

```jsx
interface HeaderProps {
  type: "login" | "main" | "instructor" | "participant";
}
```
