### ISSUE TITLE
Feature: 강의자가 원할 때 강의자의 음성을 음소거/해제 사용할 수 있다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#66]
## Feature Description

여기에 작성하세요

## To-Do

- [x] 강의자가 원할 때 강의자의 음성을 음소거/해제 사용할 수 있다.
- [x] 음소거/해제 내용이 강의자 헤더 볼륨 바에 반영된다
- [x] 음소거/해제 내용이 참여자에게 반영된다 (로컬 서버로 확인)

### 추가 사항

여기에 작성하세요
