### ISSUE TITLE
Feature: 설정 모달에서 입력 장치를 선택하고 음량을 설정할 수 있다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#67]
## Feature Description

여기에 작성하세요

## To-Do

- [x] 입력 장치를 선택할 수 있다.
- [x] 입력 장치 선택 select 태그를 분리하고, 값을 recoil을 이용해서 저장하고 사용한다.
- [x] 입력되는 음량을 slider 바를 이용해서 설정할 수 있다.
- [x] 실제로 잘 전송되는지 확인한다.

### 추가 사항

여기에 작성하세요

고민 1 : 어떻게 음량을 설정해야 하는가?

고민 2 : 어떻게 설정한 음량을 mediaStream에 반영해야 하는가?

처음에는 원본 mediaStream에서 추출한 오디오를 gainNode로 음량을 조절하고, 그 결과를 원본 mediaStream에 반영하려고 했으나 잘 되지 않았습니다.
여러 방법을 고민한 끝에

결과적으로 원본 
사용자에게서 원본 mediaStream 받음 -> mediaStream 에서 오디오 트랙 추출 -> setupAudioAnalysis에서 오디오 트랙 변조 -> 변조한 트랙을 새 updatedStream에 추가 -> updatedStream을 mediaServer로 전송

이 과정은 주말까지 더 잘 정리해서 올릴게요
