### ISSUE TITLE
Feature: 음성 파형과 강의 진행 시간을 표시한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#69]
## Feature Description

여기에 작성하세요

## To-Do

- [x] 음성 파형 구현
- [x] 강의 진행 시간 (마이크 입력 시작 후 시간) 표시 
- [x] 음성 파형 컴포넌트화
- [x] 헤더에 연결

### 추가 사항

https://github.com/boostcampwm2023/web13_Boarlog/assets/86391351/cbb9d981-536a-412d-b58f-79e869956a23
