### ISSUE TITLE
Feature: 참여자 헤더 정보를 표시할 수 있다. (강의 나가기 등)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#73]
## Feature Description

여기에 작성하세요

## To-Do

- [x] 참여자 헤더에 볼륨 바와 진행시간을 표시한다.
- [x] 참여자 헤더에 강의 나가기 버튼을 표시한다.
- [x] 참여자 헤더에서 설정 버튼을 눌러 스피커 조절 모달을 표시한다.

### 추가 사항

여기에 작성하세요
