### ISSUE TITLE
Feature: 마이 페이지를 확인할 수 있다. (UI 작업)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#76]
## Feature Description
마이 페이지를 확인할 수 있다. (UI 작업) #76

## To-Do
- [x] 마이 페이지 UI 구성
- [x] 더미 데이터 추가, 더미 데이터 기준으로 강의 다시보기 리스트 구성
- [x] 마이 페이지 닉네임 수정 기능 추가
- [x] header 높이 변경 (`5rem`)
- [x] header 반응형 작업
- [x] start 페이지와 마이 페이지 닉네임 입력 관련 수정
- [x] enter 키 관련 이벤트 추가
- [x] login, start, main, mypage 간 정적 연결

### 추가 사항
마이 페이지 UI를 구현하였습니다. 더미 데이터를 바탕으로 강의 다시보기 리스트가 표시되도록 작업하였으며, 일부 페이지들의 요소를 반응형을 작업하였습니다.

기존에 추가하였던 `lg`, `st`의 경우는 의미를 알아보기 어려워 이를 제거하고 `tailwindCSS`에서 기본적으로 제공하는 태그를 활용하였습니다. 또한 `Home` 페이지의 경우는 특정 너비가 기준으로 필요하기 때문에 기존의 `hm`을 `home`으로 변경하였습니다.

이번 PR에서 반응형으로 작업한 부분은 아래와 같습니다.
- header setting modal
- header profile modal
- header buttons
- header logo
- mypage

### instructor 페이지 반응형

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/34720411-f576-4d7a-9cc2-0b338c60820c

### participant 페이지 반응형

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/57faeaac-71e3-435d-a32f-ec3055d2adef

### modal 반응형

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/c018b0c1-14a5-4c74-a3d7-d8a2446b432c

### mypage 반응형

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/b96898e5-d0f4-45d2-b614-2c717d028ea7

### mypage 닉네임 입력 관련 추가 작업

https://github.com/boostcampwm2023/web13_Boarlog/assets/79556112/57bfad5c-e36c-491d-9836-ab9ae326fc3d
