### ISSUE TITLE
Feature: 서버로부터 지난 강의 기록을 불러온 후 화면에 리스트를 렌더링시킨다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#77]
## Feature Description
마이 페이지 관련 API 연동 작업

## To-Do

- [ ] 닉네임과 이메일 표시 (local storage)
- [ ] 닉네임 변경 관련 API 연결
- [ ] 강의 기록 관련 API 요청
