### ISSUE TITLE
Feature: 서버는 구글 계정 정보를 활용하여 구글 프로필 이미지와 닉네임을 전달한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#8]
## Feature Description

OAuth를 활용한 구글 로그인 구현을 위해서 구글 사용자 정보를 가져오는 기능을 구현했습니다. 사용자가 최초 로그인 한 회원이라면 회원가입을 진행시키기 위해 회원가입 기능도 작성했습니다.

## To-Do

- [x] 구글 로그인을 통한 사용자 정보 가져오기
- [x] 최초 로그인 한 유저를 위한 회원가입 기능
- [x] 회원가입을 위한 DB 연결 및 User 스키마 생성
