### ISSUE TITLE
Feature: ‘지우개’ 버튼을 클릭하여 지우기 모드로 전환할 수 있다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#92]
## Feature Description
지우개 모드 기능 구현

## To-Do

- [x] 지우개 버튼 클릭시 커서 변경
- [x] 요소 클릭시 해당 요소 제거
- [x] 블록지정으로 선택된 요소들 제거
